[package]
name = "amg2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rusqlite = { version = "0.31.0", features = ["bundled"] }
regex = "1.10.4"
